import React from 'react'
import { IonGrid, IonImg, IonRow, IonSpinner, IonText } from '@ionic/react'

import './css/StatusScreen.css'

interface LoadingScreenProps {
  text: string
}

export function LoadingIndicator({ text }: LoadingScreenProps) {
  return (
    <IonGrid className="statusContainer">
      <IonRow>
        <IonImg className="statusContainer__image" src="/images/loading.png"></IonImg>
      </IonRow>
      <IonRow>
        <IonSpinner color="primary" />
      </IonRow>
      <IonRow>
        <IonText className="statusContainer__text">{text}</IonText>
      </IonRow>
      <IonRow>
        <IonText className="statusContainer__credentials">This image was generated by Microsoft CoPilot.</IonText>
      </IonRow>
    </IonGrid>
  )
}
